### ISSUE TITLE
set ми ще не вчили як використовувати

### ISSUE THREAD

**Issue by Muxamedin** [ZoryanaOleksii/test#5]
https://github.com/ZoryanaOleksii/test/blob/2ab797f3ed7c550ee2e4b4bea83ca46fc8e8d369/lesson_5/same_number.py#L4
<img width="399" alt="image" src="https://user-images.githubusercontent.com/4419752/182679888-beea5384-cf58-4ce7-a04d-acb8da9811e1.png">
set ми ще не вчили як використовувати

**Comment by ZoryanaOleksii** [comment]
Виправив помилки, залив на новий файл same_number1.py

**Comment by ZoryanaOleksii** [comment]
lesson_5/same_number1.py
